#!/bin/bash
# This script needs the credentials.csv generated by create_accounts.sh
green='\033[0;32m'
nocolor='\033[0m'
yellow='\033[0;33m'

input="credentials.csv"
while IFS=, read -r mail password; do
    new_password=$(tr </dev/urandom -dc _A-Z-a-z-0-9 | head -c${30:-32})
    curl -s -o /dev/null -H 'Content-Type: application/json' https://publicapi.solotodo.com/rest-auth/password/reset/ -d "$(
        cat <<EOF
    {
            "email": "$mail"
    }
EOF
    )"
    echo "PASSWORD RECOVERY MAIL SENT: "$mail
    login=${mail%@*}
    domain=${mail#*@}
    sleep 2

    id=$(curl -s "https://www.1secmail.com/api/v1/?action=getMessages&login=$login&domain=$domain" | jq '.[0].id')
    sleep 1

    confirmation_url=$(curl -s "https://www.1secmail.com/api/v1/?action=readMessage&login=$login&domain=$domain&id=$id" | jq '.body' | awk '{gsub(/\\n/,"\n")}1' | sed -ne 's/.*\(http[^"]*\).*/\1/p')
    confirmation_com=$(curl -s $confirmation_url | htmlq --attribute href a)
    confirmation_cl=$(curl -s $confirmation_url | htmlq --attribute href a | sed 's/com/cl/g')
    deleted_trailing_slash_url=$(echo $confirmation_com | sed 's:/*$::')
    parsed_url=${deleted_trailing_slash_url:31}
    uuid=${parsed_url%/*}
    token=${parsed_url#*/}

    curl -s -o /dev/null -H 'Content-Type: application/json' https://publicapi.solotodo.com/rest-auth/password/reset/confirm/ -d "$(
        cat <<EOF
    {
        "new_password1": "$new_password",
        "new_password2": "$new_password",
        "uid": "$uuid",
        "token": "$token"
    }
EOF
    )"
    echo -e "${green}$mail PASSWORD CHANGED SUCCESSFULLY.${nocolor} ${yellow}NEW PASSWORD: "$new_password${nocolor}

    echo $mail,$new_password >>new_credentials.csv
done <$input
