#!/bin/bash

# This script works with the credentials.csv file generated by the create_accounts.sh script
green='\033[0;32m'
nocolor='\033[0m'
yellow='\033[0;33m'

input="credentials.csv"
while IFS=, read -r mail password; do
    new_password=$(tr </dev/urandom -dc _A-Z-a-z-0-9 | head -c${30:-32})
    login_token=$(
        curl -s -H 'Content-Type: application/json' https://publicapi.solotodo.com/rest-auth/login/ -d "$(
            cat <<EOF
    {
            "email": "$mail",
            "password": "$password"
    }
EOF
        )" | jq '.key' | sed 's/"//g'
    )

    curl -s -o /dev/null -H "Authorization: Token $login_token" -H "Content-Type: application/json" https://publicapi.solotodo.com/rest-auth/password/change/ -d "$(
        cat <<EOF
    {
        "old_password": "$password",
        "new_password1": "$new_password",
        "new_password2": "$new_password"
    }
EOF
    )"

    echo -e "${green}$mail PASSWORD CHANGE SUCCESSFUL.${nocolor} ${yellow}NEW PASSWORD: "${new_password}${nocolor}
    echo $mail,$new_password >>password_change_credentials.csv
done <$input

